services:
  postgres:
    image: ankane/pgvector:v0.5.1
    restart: unless-stopped
    shm_size: "128mb"
    networks:
      - mem0_network
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "postgres", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongodb:
    image: mongo:7.0
    container_name: mem0-mongodb
    restart: on-failure
    networks:
      - mem0_network
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=mongo
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - mongodb_data:/data/db

  mem0-service:
    image: mem0-service:amd64
    restart: unless-stopped
    container_name: mem0-api
    ports:
      - "18088:8000"
    environment:
      # 在服务器上设置这些环境变量
      - DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}

      # PostgreSQL配置
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_COLLECTION=memories
      - EMBEDDING_MODEL_DIMS=1536

      # MongoDB配置
      - MONGODB_URI=mongodb://mongo:mongo@mongodb:27017/
      - MONGODB_DATABASE=mem0
      - HISTORY_DB_PATH=/app/history/history.db
      - EMBEDDING_MODEL_DIMS=1536

      # 其他配置
      - HISTORY_DB_PATH=/app/history/history.db
    volumes:
      - ./history:/app/history
    depends_on:
      postgres:
        condition: service_healthy
      mongodb:
        condition: service_healthy
    networks:
      - mem0_network

volumes:
  postgres_data:
    driver: local
  mongodb_data:
    driver: local

networks:
  mem0_network:
    driver: bridge